version: "3"
services:

  db:
    image: "postgres"
    container_name: "my_db"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - ./dbcsripts:/docker-entrypoint-initdb.d

volumes:
  postgres-data: