// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package task3

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Mother struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Firstname            string   `protobuf:"bytes,2,opt,name=Firstname,proto3" json:"Firstname,omitempty"`
	Lastname             string   `protobuf:"bytes,3,opt,name=Lastname,proto3" json:"Lastname,omitempty"`
	Patronymic           string   `protobuf:"bytes,4,opt,name=Patronymic,proto3" json:"Patronymic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Mother) Reset()         { *m = Mother{} }
func (m *Mother) String() string { return proto.CompactTextString(m) }
func (*Mother) ProtoMessage()    {}
func (*Mother) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *Mother) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mother.Unmarshal(m, b)
}
func (m *Mother) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mother.Marshal(b, m, deterministic)
}
func (m *Mother) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mother.Merge(m, src)
}
func (m *Mother) XXX_Size() int {
	return xxx_messageInfo_Mother.Size(m)
}
func (m *Mother) XXX_DiscardUnknown() {
	xxx_messageInfo_Mother.DiscardUnknown(m)
}

var xxx_messageInfo_Mother proto.InternalMessageInfo

func (m *Mother) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Mother) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *Mother) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *Mother) GetPatronymic() string {
	if m != nil {
		return m.Patronymic
	}
	return ""
}

type ListMotherRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListMotherRequest) Reset()         { *m = ListMotherRequest{} }
func (m *ListMotherRequest) String() string { return proto.CompactTextString(m) }
func (*ListMotherRequest) ProtoMessage()    {}
func (*ListMotherRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *ListMotherRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMotherRequest.Unmarshal(m, b)
}
func (m *ListMotherRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMotherRequest.Marshal(b, m, deterministic)
}
func (m *ListMotherRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMotherRequest.Merge(m, src)
}
func (m *ListMotherRequest) XXX_Size() int {
	return xxx_messageInfo_ListMotherRequest.Size(m)
}
func (m *ListMotherRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMotherRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListMotherRequest proto.InternalMessageInfo

type ListMotherResponse struct {
	Mothers              []*Mother `protobuf:"bytes,1,rep,name=Mothers,proto3" json:"Mothers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListMotherResponse) Reset()         { *m = ListMotherResponse{} }
func (m *ListMotherResponse) String() string { return proto.CompactTextString(m) }
func (*ListMotherResponse) ProtoMessage()    {}
func (*ListMotherResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *ListMotherResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMotherResponse.Unmarshal(m, b)
}
func (m *ListMotherResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMotherResponse.Marshal(b, m, deterministic)
}
func (m *ListMotherResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMotherResponse.Merge(m, src)
}
func (m *ListMotherResponse) XXX_Size() int {
	return xxx_messageInfo_ListMotherResponse.Size(m)
}
func (m *ListMotherResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMotherResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListMotherResponse proto.InternalMessageInfo

func (m *ListMotherResponse) GetMothers() []*Mother {
	if m != nil {
		return m.Mothers
	}
	return nil
}

func init() {
	proto.RegisterType((*Mother)(nil), "task3.Mother")
	proto.RegisterType((*ListMotherRequest)(nil), "task3.ListMotherRequest")
	proto.RegisterType((*ListMotherResponse)(nil), "task3.ListMotherResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 209 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2d, 0x49, 0x2c, 0xce, 0x36,
	0x56, 0x2a, 0xe2, 0x62, 0xf3, 0xcd, 0x2f, 0xc9, 0x48, 0x2d, 0x12, 0xe2, 0xe3, 0x62, 0xca, 0x4c,
	0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0e, 0x62, 0xca, 0x4c, 0x11, 0x92, 0xe1, 0xe2, 0x74, 0xcb,
	0x2c, 0x2a, 0x2e, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x0c, 0x42, 0x08,
	0x08, 0x49, 0x71, 0x71, 0xf8, 0x24, 0x42, 0x25, 0x99, 0xc1, 0x92, 0x70, 0xbe, 0x90, 0x1c, 0x17,
	0x57, 0x40, 0x62, 0x49, 0x51, 0x7e, 0x5e, 0x65, 0x6e, 0x66, 0xb2, 0x04, 0x0b, 0x58, 0x16, 0x49,
	0x44, 0x49, 0x98, 0x4b, 0xd0, 0x27, 0xb3, 0xb8, 0x04, 0x62, 0x6f, 0x50, 0x6a, 0x61, 0x69, 0x6a,
	0x71, 0x89, 0x92, 0x2d, 0x97, 0x10, 0xb2, 0x60, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x90, 0x3a,
	0x17, 0x3b, 0x44, 0xa4, 0x58, 0x82, 0x51, 0x81, 0x59, 0x83, 0xdb, 0x88, 0x57, 0x0f, 0xec, 0x6e,
	0x3d, 0xa8, 0x3a, 0x98, 0xac, 0x91, 0x0f, 0x17, 0xbb, 0x27, 0xd4, 0x23, 0x8e, 0x5c, 0x5c, 0x08,
	0x93, 0x84, 0x24, 0xa0, 0x1a, 0x30, 0x6c, 0x94, 0x92, 0xc4, 0x22, 0x03, 0xb1, 0x36, 0x89, 0x0d,
	0x1c, 0x46, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x66, 0x1c, 0x5b, 0x72, 0x34, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// IMotherClient is the client API for IMother service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IMotherClient interface {
	ListMother(ctx context.Context, in *ListMotherRequest, opts ...grpc.CallOption) (*ListMotherResponse, error)
}

type iMotherClient struct {
	cc *grpc.ClientConn
}

func NewIMotherClient(cc *grpc.ClientConn) IMotherClient {
	return &iMotherClient{cc}
}

func (c *iMotherClient) ListMother(ctx context.Context, in *ListMotherRequest, opts ...grpc.CallOption) (*ListMotherResponse, error) {
	out := new(ListMotherResponse)
	err := c.cc.Invoke(ctx, "/task3.IMother/ListMother", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IMotherServer is the server API for IMother service.
type IMotherServer interface {
	ListMother(context.Context, *ListMotherRequest) (*ListMotherResponse, error)
}

// UnimplementedIMotherServer can be embedded to have forward compatible implementations.
type UnimplementedIMotherServer struct {
}

func (*UnimplementedIMotherServer) ListMother(ctx context.Context, req *ListMotherRequest) (*ListMotherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMother not implemented")
}

func RegisterIMotherServer(s *grpc.Server, srv IMotherServer) {
	s.RegisterService(&_IMother_serviceDesc, srv)
}

func _IMother_ListMother_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMotherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IMotherServer).ListMother(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task3.IMother/ListMother",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IMotherServer).ListMother(ctx, req.(*ListMotherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _IMother_serviceDesc = grpc.ServiceDesc{
	ServiceName: "task3.IMother",
	HandlerType: (*IMotherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListMother",
			Handler:    _IMother_ListMother_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
